### ISSUE TITLE
manual override

### ISSUE THREAD

**Issue by rocket-pig** [kabiroberai/libswift#2]
...since we already have the swift toolchain from following the installation instructions at:
https://github.com/theos/theos/wiki/Installation-Linux
(which is basically just  `curl https://kabiroberai.com/toolchain/download.php?toolchain=swift-ubuntu-latest-Lo swift-toolchain.tar.gz`
 and then unpacking that to $THEOS/toolchains/swift)

on phone:
mkdir /usr/lib/libswift
mkdir /usr/lib/libswift/stable
bash /usr/libexec/cydia/move.sh /usr/lib/libswift/stable #(this makes dir a symlink into /var/stash/) 

on computer:
cd $(THEOS)/toolchain/swift/lib/swift/iphoneos
scp -v libswift*.dylib phone:/usr/lib/libswift/stable/

¯\_(ツ)_/¯

**Comment by kabiroberai** [comment]
The open source toolchain is a little different from the Apple one distributed in the `org.swift.libswift` package, and there might be further changes in the future. 

Additionally, it’s necessary to depend on `org.swift.libswift` to ensure that regular users can install your package. Once you do this, installing your own Swift libraries can result in conflicts.
